// Detailed content for profection year and solar return interpretations.

export const PLANET_AS_YEAR_LORD = {
  Sun: {
    title: 'The Illuminator',
    glyph: '☉',
    archetype: 'A year of identity, vitality, and creative self-expression. The Sun as year lord illuminates who you are and who you are becoming — matters of ego, leadership, life direction, and creative purpose take center stage.',
    asLord: 'When the Sun governs your year, you are called to step into your light. This is a year to be seen, to lead, and to clarify what you truly want. Your vitality and sense of self are heightened. Relationships with father figures, authority, or children may feature prominently.',
    natalPlacementMeans: 'Where the Sun sits in your birth chart reveals the life area that will be most illuminated and activated this year — the stage on which your solar drama unfolds.',
    watchOuts: 'Ego conflicts, burnout from overexposure, or centering yourself at others\' expense.',
  },
  Moon: {
    title: 'The Nurturer',
    glyph: '☽',
    archetype: 'A year of emotional depth, home, family, and inner rhythms. The Moon as year lord turns attention inward — to feelings, memories, instincts, and what nourishes you at the deepest level.',
    asLord: 'When the Moon governs your year, your emotional life intensifies. Expect matters of home, family, motherhood, emotional security, and belonging to dominate. Dreams and intuition are heightened. This is a year to tend your inner garden and strengthen the roots that sustain you.',
    natalPlacementMeans: 'Where the Moon sits in your birth chart shows the life area where emotional tides will rise highest this year — where you will feel things most deeply and where comfort and security are sought.',
    watchOuts: 'Mood swings, emotional dependency, retreating from the world, or clinging to the past.',
  },
  Mercury: {
    title: 'The Messenger',
    glyph: '☿',
    archetype: 'A year of communication, learning, and connection. Mercury as year lord activates the mind — ideas, conversations, writing, commerce, and the exchange of information flow freely.',
    asLord: 'When Mercury governs your year, expect a busy, mentally stimulating period with lots of movement, short trips, and social interaction. This is a year to learn, teach, negotiate, sign contracts, and follow your curiosity. Your adaptability is your greatest asset.',
    natalPlacementMeans: 'Where Mercury sits in your birth chart reveals the life area where communication, learning, and intellectual exchange will be most active and rewarding this year.',
    watchOuts: 'Scattered energy, overthinking, gossip, or failing to follow through on promises.',
  },
  Venus: {
    title: 'The Beloved',
    glyph: '♀',
    archetype: 'A year of love, beauty, values, and pleasure. Venus as year lord brings matters of the heart to the foreground — relationships, attraction, aesthetics, and what you genuinely value.',
    asLord: 'When Venus governs your year, expect themes of romance, partnership, financial matters, creative beauty, and reconciliation. This is a year to cultivate what you love, deepen your connections, and align your choices with your authentic values. What you attract matters as much as what you pursue.',
    natalPlacementMeans: 'Where Venus sits in your birth chart shows the life area where love, beauty, and material rewards will bloom most abundantly this year — where you will find pleasure and draw others to you.',
    watchOuts: 'Indulgence, people-pleasing, superficiality, or staying in relationships out of comfort rather than growth.',
  },
  Mars: {
    title: 'The Warrior',
    glyph: '♂',
    archetype: 'A year of drive, action, assertion, and desire. Mars as year lord ignites your ambitions and fuels your courage to pursue what you want with intensity and directness.',
    asLord: 'When Mars governs your year, expect forward momentum, conflict resolution (sometimes through confrontation), physical energy, and the will to initiate. This is a year to compete, defend your boundaries, and channel your passion into something worth fighting for. Independence and self-reliance are rewarded.',
    natalPlacementMeans: 'Where Mars sits in your birth chart reveals the life area where you will be most driven, competitive, and action-oriented this year — the arena where your energy and courage are most needed.',
    watchOuts: 'Impulsiveness, aggression, burnout, conflict for its own sake, or steamrolling others.',
  },
  Jupiter: {
    title: 'The Expander',
    glyph: '♃',
    archetype: 'A year of expansion, opportunity, growth, and meaning. Jupiter as year lord opens doors, broadens horizons, and brings optimism, abundance, and the desire to reach beyond the familiar.',
    asLord: 'When Jupiter governs your year, expect themes of travel, higher education, belief systems, legal matters, and good fortune. This is a year to say yes, take calculated risks, and trust that growth comes from stepping beyond your comfort zone. Generosity — both giving and receiving — amplifies your gains.',
    natalPlacementMeans: 'Where Jupiter sits in your birth chart reveals the life area where growth, opportunity, and abundance will flow most freely this year — where doors open and horizons widen.',
    watchOuts: 'Overextending, excess, complacency from too much ease, or making promises you cannot keep.',
  },
  Saturn: {
    title: 'The Builder',
    glyph: '♄',
    archetype: 'A year of structure, responsibility, discipline, and mastery. Saturn as year lord brings focus, hard work, and the reckoning with time — it asks you to build foundations that will last.',
    asLord: 'When Saturn governs your year, expect themes of career, authority, commitment, and the need to take responsibility. This is a year to consolidate your efforts, do the hard work that earns lasting respect, and mature through challenge. Saturn rewards patience and persistence — what you build now endures.',
    natalPlacementMeans: 'Where Saturn sits in your birth chart reveals the life area where you will be tested, disciplined, and asked to build lasting structures this year — where effort invested now compounds over time.',
    watchOuts: 'Heaviness, self-criticism, isolation, fear of failure, or becoming rigid under pressure.',
  },
};

export const PROFECTION_HOUSE_DETAILS = {
  1: {
    title: 'The House of Self',
    whatActivates: 'Identity, appearance, vitality, personal initiative, how you present to the world.',
    whatToExpect: 'A year of personal reinvention. You may change your appearance, take on a leadership role, or feel a powerful urge to redefine who you are. New beginnings, fresh starts, and a heightened sense of "this is my time" pervade. People respond to you differently — you are more visible.',
    focusAreas: 'Clarify your goals, invest in self-development, take initiative on personal projects, update your image, step into visibility.',
    watchOuts: 'Self-centeredness, impulsiveness, identity crises, or overextending yourself.',
  },
  2: {
    title: 'The House of Resources',
    whatActivates: 'Money, possessions, values, self-worth, material security.',
    whatToExpect: 'A year focused on what you earn, own, and truly value. Income may fluctuate or shift. You will be asked to clarify what matters to you at a practical level — what is worth investing in, and what you should let go. Questions of self-worth and money are deeply intertwined.',
    focusAreas: 'Budgeting and financial planning, negotiating your value, acquiring skills that increase earning power, decluttering what no longer serves you.',
    watchOuts: 'Materialism, financial overreach, tying self-worth to net worth, or hoarding.',
  },
  3: {
    title: 'The House of Communication',
    whatActivates: 'Mind, speech, writing, learning, siblings, neighbors, short trips, immediate environment.',
    whatToExpect: 'A year of mental stimulation and connection. Expect lots of conversation, ideas, writing projects, short journeys, and interaction with your local community. Siblings and neighbors may feature prominently. You may take a course, start a blog, or have conversations that reshape your thinking.',
    focusAreas: 'Improve communication skills, learn something new, write regularly, strengthen sibling and neighbor bonds, explore your local area.',
    watchOuts: 'Scattered energy, gossip, information overload, or saying yes to too many things.',
  },
  4: {
    title: 'The House of Home & Family',
    whatActivates: 'Home, family, roots, emotional foundations, the past, private life.',
    whatToExpect: 'A year to tend your roots. Expect shifts in your living situation — moving, renovating, or deepening your sense of home. Family matters come to the foreground — parents, children, or ancestral patterns that need attention. Inner emotional work is as important as outer changes.',
    focusAreas: 'Create a home that nourishes you, heal family patterns, connect with parents or children, honor your need for retreat and privacy.',
    watchOuts: 'Getting stuck in the past, emotional regression, family conflicts, or isolating yourself.',
  },
  5: {
    title: 'The House of Creativity & Joy',
    whatActivates: 'Creativity, romance, children, play, self-expression, pleasure, risk-taking.',
    whatToExpect: 'A year to follow your joy. Creative projects flourish, romance blossoms, and you may find yourself drawn to play, performance, or artistic expression. Matters involving children — your own or others\' — may be significant. This is a year to take creative risks and rediscover what makes you feel alive.',
    focusAreas: 'Pursue creative passions, date with intention, spend time with children, take calculated creative risks, prioritize joy.',
    watchOuts: 'Drama in romance, reckless speculation, creative blocks from perfectionism, or prioritizing fun over responsibility.',
  },
  6: {
    title: 'The House of Health & Daily Routine',
    whatActivates: 'Health, work, daily habits, service, routines, pets, small animals.',
    whatToExpect: 'A year to refine the machinery of your daily life. Expect focus on health — diet, exercise, and wellness routines. Your work environment and daily habits come under scrutiny. You may change jobs, adopt a new health practice, or restructure your schedule to better serve your wellbeing.',
    focusAreas: 'Establish sustainable health routines, optimize your work process, serve others meaningfully, attend to small details, care for your body.',
    watchOuts: 'Overwork, health anxiety, perfectionism, or neglecting the big picture for the small.',
  },
  7: {
    title: 'The House of Partnerships',
    whatActivates: 'Marriage, business partnerships, contracts, significant others, open enemies.',
    whatToExpect: 'A year defined by relationships. Expect partnerships to take center stage — romantic, business, or collaborative. You may marry, commit, form a business alliance, or confront tensions in existing partnerships. The mirror of relationship shows you who you are and who you are becoming.',
    focusAreas: 'Deepen your primary relationship, form strategic alliances, negotiate fair contracts, resolve conflicts, learn to balance self and other.',
    watchOuts: 'Losing yourself in others, conflict avoidance, entering partnerships too hastily, or holding grudges.',
  },
  8: {
    title: 'The House of Transformation',
    whatActivates: 'Shared resources, intimacy, death and rebirth, inheritances, debts, psychological depth.',
    whatToExpect: 'A year of deep change. Expect matters involving shared finances, debts, taxes, or inheritances. On a psychological level, you may undergo profound transformation — old patterns dying, new aspects of yourself emerging. Intimacy deepens. What is hidden comes to light.',
    focusAreas: 'Face fears and shadow material, resolve debts, deepen intimacy, process grief or loss, embrace endings as doorways to new beginnings.',
    watchOuts: 'Obsession, power struggles, financial entanglements, or resisting necessary change.',
  },
  9: {
    title: 'The House of Meaning',
    whatActivates: 'Higher education, travel, philosophy, beliefs, publishing, foreign cultures, spirituality.',
    whatToExpect: 'A year to expand your horizons. Expect travel — especially long-distance — and engagement with foreign cultures or new belief systems. You may return to school, publish your work, or have experiences that reshape your worldview. The search for meaning and truth becomes central.',
    focusAreas: 'Travel with purpose, study deeply, examine your beliefs, publish or share your knowledge, seek mentorship.',
    watchOuts: 'Dogmatism, escapist travel, overcommitting to study while neglecting daily life, or spiritual bypassing.',
  },
  10: {
    title: 'The House of Career & Calling',
    whatActivates: 'Career, public standing, reputation, authority, legacy, achievement.',
    whatToExpect: 'A year of ambition and visibility. Expect significant developments in your career or public role — promotion, recognition, a new direction, or increased responsibility. Your reputation and public image matter. You are called to step into authority and build something that outlasts you.',
    focusAreas: 'Set ambitious career goals, build your public reputation, take on leadership, mentor others, align your work with your calling.',
    watchOuts: 'Workaholism, reputation damage, sacrificing personal life for status, or chasing authority for its own sake.',
  },
  11: {
    title: 'The House of Community & Vision',
    whatActivates: 'Friendships, groups, networks, hopes, dreams, future vision, social causes.',
    whatToExpect: 'A year of connection and collective endeavor. Expect your social circle to expand or shift. Friendships become significant, and you may join groups, movements, or communities aligned with your values. Your hopes and dreams for the future clarify. Collaboration yields more than solo effort.',
    focusAreas: 'Strengthen friendships, join or lead groups, clarify your long-term vision, contribute to causes you believe in, network strategically.',
    watchOuts: 'Groupthink, losing individuality in the crowd, overcommitting to too many communities, or unrealistic dreams without action.',
  },
  12: {
    title: 'The House of Solitude & Soul',
    whatActivates: 'Retreat, solitude, spirituality, the unconscious, healing, hidden matters, endings.',
    whatToExpect: 'A year of turning inward. Expect a pull toward solitude, spiritual practice, and reflection. The outer world may feel quieter as you process, heal, and integrate. You may confront fears, work through subconscious patterns, or prepare for a new cycle. Endings are significant — they clear space for what is next.',
    focusAreas: 'Prioritize rest and spiritual practice, attend therapy or inner work, complete unfinished cycles, listen to your dreams, retreat to recharge.',
    watchOuts: 'Isolation, escapism, depression, spiritual bypassing, or avoiding necessary closure.',
  },
};

// What it means when the year lord is currently transiting through a particular natal house
export const TRANSIT_HOUSE_INTERPRETATION = {
  1: 'energizing your sense of self and personal initiative',
  2: 'activating matters of money, values, and resources',
  3: 'stimulating communication, learning, and connections',
  4: 'touching your home, family, and emotional roots',
  5: 'igniting creativity, romance, and play',
  6: 'focusing on health, work, and daily routines',
  7: 'highlighting partnerships and significant relationships',
  8: 'stirring transformation, intimacy, and shared resources',
  9: 'expanding horizons, beliefs, and the search for meaning',
  10: 'elevating career, public standing, and ambition',
  11: 'activating friendships, community, and future vision',
  12: 'drawing you inward to rest, reflect, and heal',
};